# -*- coding: utf-8 -*-
"""Proyek Analisis Data_Dicoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uaPpaxRROSkvAw8bUWDa9Skd2xYxHwRi

Proyek Analisis Data: Bike Sharing

# Menentukan Pertanyaan Bisnis



* 1. Pada bulan apa penyewaan sepeda mendapat order terbanyak dalam periode 1 tahun?
* 2. Pada Musim apa penyewaan sepeda mendapat order terbanyak dalam periode 1 tahun?
* 3. Apakah ada perbedaan antara hari kerja dan hari libur dalam jumlah sewa harian?
* 4. Apakah ada pola berdasarkan jam dalam jumlah sewa sepeda harian?

Menyiapkan Library yang dibutuhkan
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import zipfile

"""# Data Wrangling

Gathering Data
"""

! chmod 600 /content/kaggle.json

! KAGGLE_CONFIG_DIR=/content/ kaggle datasets download -d lakshmi25npathi/bike-sharing-dataset

zip_file = zipfile.ZipFile('/content/bike-sharing-dataset.zip', 'r')
zip_file.extractall('/content')

df_day = pd.read_csv("/content/day.csv")
df_day.head()

df_hour = pd.read_csv("/content/hour.csv")
df_hour.head()

"""Assessing Data

1. Menilai tabel df_day
"""

df_day.info()

# Mengecek missing Values
df_day.isna().sum()

# Mengecek Data Duplikat
print('jumlah duplikasi data :',df_day.duplicated().sum())

"""2. Menilai tabel df_hour"""

df_hour.info()

print(df_hour.shape)

# Mengecek missing Values
df_hour.isna().sum()

# Mengecek Data Duplikat
print('jumlah duplikasi data :',df_hour.duplicated().sum())

"""Cleaning Data

Semua tipe data sudah sesuai dan tidak ada masalah

# Exploratory Data Analysis (EDA)

Merge Data frame
"""

df_bike = df_hour.merge(df_day, on='dteday', how='inner', suffixes=('_hourly', '_daily'))
df_bike.head()

# Konversi nilai untuk kolom 'season' : 1:Winter, 2:Spring, 3:Summer, 4:Fall
df_bike.season_hourly.replace((1,2,3,4), ('Winter','Spring','Summer','Fall'), inplace=True)
df_bike.season_daily.replace((1,2,3,4), ('Winter','Spring','Summer','Fall'), inplace=True)

# Konversi nilai untuk kolom 'yr' : 0:2011, 1:2012
df_bike.yr_hourly.replace((0,1), (2011,2012), inplace=True)
df_bike.yr_daily.replace((0,1), (2011,2012), inplace=True)

# Konversi nilai untuk kolom 'mnth' :  1:Jan, 2:Feb, 3:Mar, 4:Apr, 5:May, 6:Jun, 7:Jul, 8:Aug, 9:Sep, 10:Oct, 11:Nov, 12:Dec
df_bike.mnth_hourly.replace((1,2,3,4,5,6,7,8,9,10,11,12),('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'), inplace=True)
df_bike.mnth_daily.replace((1,2,3,4,5,6,7,8,9,10,11,12),('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'), inplace=True)

# Konversi nilai untuk kolom 'weathersit' : 1:Clear, 2:Misty, 3:Light_RainSnow 4:Heavy_RainSnow
df_bike.weathersit_hourly.replace((1,2,3,4), ('Clear','Misty','Light_RainSnow','Heavy_RainSnow'), inplace=True)
df_bike.weathersit_daily.replace((1,2,3,4), ('Clear','Misty','Light_RainSnow','Heavy_RainSnow'), inplace=True)

# Konversi nilai untuk kolom 'weekday' : 0:Sun, 1:Mon, 2:Tue, 3:Wed, 4:Thu, 5:Fri, 6:Sat
df_bike.weekday_hourly.replace((0,1,2,3,4,5,6), ('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'), inplace=True)
df_bike.weekday_daily.replace((0,1,2,3,4,5,6), ('Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'), inplace=True)


# Konversi nilai untuk kolom 'workingday' : 0:No, 1:Yes
df_bike.workingday_hourly.replace((0,1), ('Hari Libur', 'Hari Kerja'), inplace=True)

df_bike.head()

df_bike.describe(include="all")

"""Boxplot Pengguna Bike sharing Berdasarkan Bulan

"""

plt.figure(figsize=(16,6))

# Create a boxplot using the sns.boxplot() function
sns.boxplot(
    x="mnth_daily",
    y="cnt_daily",
    data=df_bike,
    palette=["Darkseagreen", "Mintcream"]
)

# Add labels and a title to the plot
plt.xlabel("Bulan")
plt.ylabel("Total Penyewa")
plt.title("Total Penyewa Sepeda Berdasarkan Bulan")

# Show the plot
plt.show()

"""* Bike sharing memiliki permintaan tertinggi pada periode bulan Juni hingga bulan September.

Boxplot Pengguna Bike sharing Berdasarkan Musim
"""

plt.figure(figsize=(16,6))

# Create a boxplot using the sns.boxplot() function
sns.boxplot(
    x="season_daily",
    y="cnt_daily",
    data=df_bike,
    palette=["Darkseagreen", "Mintcream"]
)

# Add labels and a title to the plot
plt.xlabel("Musim")
plt.ylabel("Total Penyewa")
plt.title("Total Penyewa Sepeda Berdasarkan Musim")

# Show the plot
plt.show()

"""*   Bikesharing memiliki permintaan tertinggi pada musim Summer atau musim panas.

Pointplot Pengguna Bike Sharing Berdasarkan musim dan Jam
"""

fig, ax = plt.subplots(figsize=(20,5))
sns.pointplot(data=df_bike, x='hr', y='cnt_hourly', hue='season_daily')
# Add labels and a title to the plot
plt.xlabel("Jam")
plt.ylabel("Total Pennyewa")
ax.set(title="Total Penyewa Berdasarkan Musim dan Jam")

"""*   Penyewaan sepeda memilik permintaan tertinggi pada jam 17.00 atau jam 5 pm pada setiap musim.
*   Penyewaan sepeda memilik permintaan tertinggi pada musim summer atau musim panas.

Boxplot Perbedaan jumlah sewa sepeda harian antara hari kerja dan hari libur
"""

# Perbandingan hari kerja dan hari libur
plt.figure(figsize=(8, 5))
sns.boxplot(x="workingday_daily", y="cnt_daily", data=df_bike, palette = "Set3")
plt.title("Perbedaan Antara Hari Kerja dan Hari Libur dalam Jumlah Sewa Sepeda Harian")
plt.xlabel("Hari Kerja")
plt.ylabel("Jumlah Sewa Sepeda Harian")
plt.show()

"""*   Terdapat perbedaan penyewaan sepeda antara hari kerja dan hari libur dimana penyewaan lebih banyak pada hari kerja

Barplot Penyewaan Sepeda Berdasarkan Hari
"""

fig, ax = plt.subplots(figsize=(20,5))
sns.barplot(data=df_bike, x='weekday_daily', y='cnt_daily', ax=ax, palette = "Set3")
ax.set(title='Total Penyewa Sepeda Berdasarkan Hari')

"""*   Total penyewaan terbanyak pada hari Thursday atau Kamis dan hari Friday atau Jumat

# Explanatory Data Analysis & Data Visualization

1. Pada bulan apa penyewaan sepeda mendapat order terbanyak dalam periode 1 tahun?
"""

plt.figure(figsize=(10,6))

sns.barplot(x='mnth_daily', y='cnt_daily', data=df_bike, hue='yr_daily', palette = "Set2")

plt.xlabel("Bulan")
plt.ylabel("Total Penyewa")
plt.title("Total Penyewa Sepeda Berdasarkan Bulan")

plt.show()

"""*   Penyewaan sepeda memilik permintaan tertinggi pada bulan Juni untuk tahun 2011.
*  Penyewaan sepeda memiliki permintaan tertinggi pada bulan September untuk tahun 2012.

2. Pada musim apa penyewaan sepeda mendapat order terbanyak dalam periode 1 tahun?
"""

plt.figure(figsize=(10,6))

sns.barplot(x='season_daily', y='cnt_daily', data=df_bike, hue='yr_daily', palette = "Set2")

plt.xlabel("Musim")
plt.ylabel("Total Penyewa")
plt.title("Total Penyewa Sepeda Berdasarkan Musim")

plt.show()

"""*   Penyewaan sepeda memiliki permintaan tertinggi pada musim summer atau musim panas untuk tahun 2011 dan 2012

3. Apakah ada perbedaan antara hari kerja (workingday) dan hari libur (holiday) dalam jumlah sewa sepeda harian?
"""

avg_holiday = df_bike.groupby('holiday_daily')['cnt_daily'].mean().reset_index().sort_values("cnt_daily")

plt.figure(figsize=(8, 5))
sns.barplot(x='holiday_daily', y='cnt_daily', data=avg_holiday, palette='Set1')

plt.title('Rata-rata Penyewaan Sepeda pada Hari Libur')
plt.xlabel('Hari Libur')
plt.ylabel('Rata-rata Penyewaan')
plt.xticks([0, 1], ['Tidak Libur', 'Libur'])

plt.show()

"""*   Rata - rata penyewaan terjadi saat hari tidak libur ( Senin - Jumat )

4. Apakah ada pola berdasarkan jam dalam jumlah sewa sepeda harian?
"""

rental_jam = df_bike.groupby('hr')['cnt_hourly'].mean()

plt.bar(rental_jam.index, rental_jam.values, color='#F08080')

plt.title('Pola Jumlah Sewa Sepeda Harian Berdasarkan Jam')
plt.xlabel('Jam')
plt.ylabel('Jumlah Sewa Sepeda Harian')

plt.show()

"""*   pada grafik diatas dapat dilihat bahwa waktu sewa lebih banyak terjadi pada sekitar jam 17.00 atau jam 5 pm

# Conclusion

1. Pada bulan apa penyewaan sepeda mendapat order terbanyak dalam periode 1 tahun?
*   penyewaan sepeda mendapat order terbanyak pada bulan Juni untuk tahun 2011 dan pada bulan September untuk tahun 2012.

2. Pada musim apa penyewaan sepeda mendapat order terbanyak dalam periode 1 tahun?
*   Musim summer atau musim panas merupakan musim yang memiliki penyewa sepeda terbanyak dalam periode 1 tahun.

3. Apakah ada perbedaan antara hari kerja (workingday) dan hari libur (holiday) dalam jumlah sewa sepeda harian?

*   Jumlah sewa sepeda lebih banyak ketika hari kerja daripada hari libur.
*   Total penyewaan terbanyak pada hari Thursday atau Kamis dan hari Friday atau Jumat

4. Apakah ada pola berdasarkan jam dalam jumlah sewa sepeda harian?

*   Jumlah sewa sepeda meningkat sekitar jam 17.00 atau jam 5 pm.
"""